name: DokcerBuildAction
description: Build docker images.
author: DavidJones

inputs:
  username:
    description: 'GitHub Container Registry Username'
    required: true
    default: ''
  password:
    description: 'GitHub Container Registry Password'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs:username }}
        password: ${{ inputs:password }}

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Compile codes
      shell: bash
      run: pnpm compile
