name: Publish Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build docker image
        uses: DavidKk/ai-assistant-wechat/.github/actions/build-docker-image@main
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/davidkk/ai-assistant-wechat:alpha
